version: '3.7'

services:
  api:
    container_name: oxehealth-api
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports: 
      - 5000:5000
    networks:
      - oxehealth
    depends_on:
      - mysql
  client: 
    container_name: oxehealth-client
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app  
    ports: 
      - 5001:5001 
    networks:
      - oxehealth
  mysql:
    container_name: oxehealth-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - oxehealth 
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql    
    restart: always    
  redis:
    container_name: oxehealth-redis
    image: redis:alpine
    command: --port 6380
    ports:
      - 6380:6380
    networks:
      - oxehealth
    volumes:
      - ./data/redis:/data/
volumes: 
  mysql:
networks:
  oxehealth:
